### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by kyzn**
Hi there! I've translated form messages to Turkish. 
Please feel free to edit/comment.
# hacktoberfest

### CODE REVIEW

**Comment by djzort** [comment]
Wow, thats great work

**Comment by djzort** [comment]
@fireartist shall we merge? can anyone speak turkish to read over it?

**Comment by djzort** [comment]
Seeking review via http://blogs.perl.org/users/dean/2017/02/turkish-speaker-needed.html

**Comment by burak** [comment]
Hi,

Another Turkish speaker here. Looks good to me.

**Comment by djzort** [comment]
thanks also @burak for taking a new moments

**Comment by burak** [comment]
Cheers :)

**Pull request merged**
