### PR TITLE
Remove links to defunct lacunaexpanse

### PR DESCRIPTION
**Pull request by spazm**
lacunaexpanse.com is dead, long live lacunaexpanse.

### CODE REVIEW

**Comment by djzort** [comment]
Thanks, although this doesnt warrant a release to CPAN

**Comment by spazm** [comment]
PS.  This was done as part of #cpan-prc

**Comment by djzort** [comment]
Awesome. Theres a bunch of other PR's that i've been merging so a release that will include this shouldn't be far down the road.

If youre after something juicer than pod changes, check out https://github.com/FormFu/HTML-FormFu/issues/24

**Comment by spazm** [comment]
Cool!

I also have some continuation of the podweaver changes you started.  Mainly adding the missing #ABSTRACT lines and removing duplicated pod.  When I build with a fresh checkout with current versions of dzil + plugins, I get a bunch of duplicated pod in the build.  Do you see the same?

**Pull request merged**
